### ISSUE TITLE
unidentifiable Chinese code

### ISSUE THREAD

**Issue by Mydreamandreality** [WebGoat/WebGoat#544] opened 2019-01-08 03:15 UTC
I want to replace the content in the file with Chinese to provide me with learning, but after launching the page, the Chinese character is garbled, I am sure that my file code is UTF8

**Comment by Mydreamandreality** [comment] 2019-01-08 03:17
IntroductionWebWolf.adoc This file

**Comment by zubcevic** [comment] 2019-03-07 13:24
I have noticed the same issue when the OS is e.g. Windows. Then the start screen also has one strange set of characters in the middle of the content. This is resolved by forcing the file encoding at start of the JVM.

java -Dfile.encoding=UTF-8 -jar webgoat-server-8.0.0.M24.jar

That might very well be the same root cause. Please try out and let us know.

**Closed** 2019-07-19 14:31 UTC
