### ISSUE TITLE
Password reset Lesson: Reset request not sent in a special circumstance

### ISSUE THREAD

**Issue by Hezq** [WebGoat/WebGoat#550] opened 2019-01-22 09:49 UTC
Found in: _WebGoat 8.0.0.M21_ 
I didn't verify if it exists in the lastest version (8.0.0.M23), since I don't have the required version of JRE.

**Problem description:**
If the user fill an **invalid** email address on the **initial page** first, then click on "_Forgot your password?_" link to do the real work. Whatever email address does the user provide, he will get NOTHING after clicking on the "_Continue_" button.

**Analyze**
When clicking on the "_Continue_" button in this circumstance, Chrome detected an error and show it in the JavaScript console:
_An invalid form control with name='email' is not focusable._

After browsing the DOM tree, I found there are 2 DIVs in the FORM, one for login, while the other for password reset. Only one DIV will be shown at one time, and the other is hidden. But all elements' validation will be triggered no matter which DIV is shown. So, if the following 3 conditions are satisfied:
1. Login DIV is hidden;
2. Element whose name is 'email' has invalid content;
3. The "Continue" button in the password reset DIV is clicked (form submitted).
The framework will find 'email' element has invalid content, and try to give a hint to the user. But since that element is hidden now, Chrome will give out the error mentioned earlier. The password reset request won't be sent, while the user see NOTHING.

**Fix Suggestion**
Remove the element validation setting.

_It might be rare for a user to encounter this problem. But once it happens (browser remembering credential for example), it will be quite annoying. Will be better to fix it._

**Comment by Hezq** [comment] 2019-01-22 10:13
Should be "Password reset Lesson **2**"

**Comment by nbaars** [comment] 2019-01-31 18:23
@Hezq thanks for reporting this issue, indeed the older version of WebGoat had this issue, but it was fixed with this commit:

```
Same form post is used and with autocomplete this does not work because all fields will be posted. The endpoint could no long distinguish between the different actions (sending e-mail and checking password)
````

Which was after release M21, at the moment we cannot reproduce the issue with version M23
If you can reproduce the issue in M23 as well please share your details and reopen this issue.
Thanks.

**Closed by nbaars** 2019-01-31 18:23 UTC
