### ISSUE TITLE
Failed to access WebGoat from host.

### ISSUE THREAD

**Issue by gitCHH** [WebGoat/WebGoat#772] opened 2020-03-28 11:19 UTC
My WebGoat runs in a Parallels Desktop Ubuntu VM. I am able to access HTTP service created by python http.server from the host. But WebGoat is not accessible. I scan the VM with nmap. 8080 not appeared, but the python's port is listed. I am confused.

**Comment by zubcevic** [comment] 2020-03-30 15:22
This is very limited information.
How did you start WebGoat and what does the log say?
Could be lots of operating system related things. Most obvious reasons could be that one or more of the default ports are already in use. 
Please clarify your problem.

**Comment by zubcevic** [comment] 2020-04-03 10:22
As the issue is not described clearly, I have to close the issue. Feel free to reopen it with more clear information

**Closed by zubcevic** 2020-04-03 10:22 UTC
Labels: waiting for input
