### ISSUE TITLE
Lab: Client side filtering - broken path

### ISSUE THREAD

**Issue by DarkHunterer** [WebGoat/WebGoat#232] opened 2016-04-06 20:42 UTC
Looks like I posted this issue on wrong WebGoat page 6 days ago, so I'm reposting it here.

You can't go through stage 2, because there is attempt of opening file with bad path. There is slash " / " symbol missing before jsp

webapps/WebGoat/plugin_extracted/plugin/ClientSideFilteringjsp/clientSideFiltering.jsp

Piece of error:

java.io.FileNotFoundException: /xxx/xxx/xxx/WebGoat/.extract/webapps/WebGoat/plugin_extracted/plugin/ClientSideFilteringjsp/clientSideFiltering.jsp (No such file or directory)
at java.io.FileInputStream.open(Native Method)
at java.io.FileInputStream.(FileInputStream.java:146)
at java.io.FileReader.(FileReader.java:72)
at org.owasp.webgoat.plugin.ClientSideFiltering.getFileContent(ClientSideFiltering.java:387)
at org.owasp.webgoat.plugin.ClientSideFiltering.doStage2(ClientSideFiltering.java:160)
at org.owasp.webgoat.lessons.SequentialLessonAdapter.createStagedContent(SequentialLessonAdapter.java:108)
at org.owasp.webgoat.plugin.ClientSideFiltering.createContent(ClientSideFiltering.java:35)
at org.owasp.webgoat.lessons.AbstractLesson.handleRequest(AbstractLesson.java:868)

Edit: Just noticed that s1 has posted it here already

**Comment by span** [comment] 2016-06-20 21:45
This should be closed as duplicate of #231.

**Comment by nbaars** [comment] 2016-07-03 09:08
Pull request has been merged, fixed.

**Closed by nbaars** 2016-07-03 09:08 UTC
