### ISSUE TITLE
Labs with Stages all throw exceptions

### ISSUE THREAD

**Issue by davewichers** [WebGoat/WebGoat#64] opened 2015-09-15 14:44 UTC
When loading any of the labs with Stages 1 through N I get stack traces like this:

Error Message: javax.servlet.ServletException: File "/plugin_extracted/plugin/CrossSiteScripting/jsp/CrossSiteScripting.jsp" not found
org.apache.jasper.JasperException: javax.servlet.ServletException: File "/plugin_extracted/plugin/CrossSiteScripting/jsp/CrossSiteScripting.jsp" not found
at org.apache.jasper.servlet.JspServletWrapper.handleJspException(JspServletWrapper.java:585)
at org.apache.jasper.servlet.JspServletWrapper.service(JspServletWrapper.java:455)
at org.apache.jasper.servlet.JspServlet.serviceJspFile(JspServlet.java:390)
at org.apache.jasper.servlet.JspServlet.service(JspServlet.java:334)
at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)

**Comment by nbaars** [comment] 2015-09-17 20:48
There was another issue related not being able to load files (#71). I cannot reproduce this issue in Windows and Linux. 

@davewichers can you verify this again after https://github.com/WebGoat/WebGoat/pull/79 has been merged into master?

Thanks,
--Nanne

**Closed** 2015-09-19 01:21 UTC
