### ISSUE TITLE
Unable to successfully run WebGoat 8 M24 - illegal reflective access  operation

### ISSUE THREAD

**Issue by scotbellamy** [WebGoat/WebGoat#574] opened 2019-03-24 22:25 UTC
I have seen other posts for this on older versions of WebGoat and using older version of Java.  However, suggestions/fixes for those don't work for me.

I am attempting to run WebGoat 8 M24 on Macbook Pro using OpenJDK 11.  I am getting the following (as others have on older versions):
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.codehaus.groovy.reflection.CachedClass (file:/Users/scotbellamy/.m2/repository/org/codehaus/groovy/groovy/2.4.15/groovy-2.4.15.jar) to method java.lang.Object.finalize()
WARNING: Please consider reporting this to the maintainers of org.codehaus.groovy.reflection.CachedClass
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release

As a result, I am unable to access the running WebGoat server on port 8080.  

I tried cloning, building, running and have the same issue.  What do I need to do to resolve this issue?

**Comment by zubcevic** [comment] 2019-03-25 05:21
#569 
did you try the correct context root? http://127.0.0.1:8080/WebGoat
is the starting point. The context root is very important.

**Comment by scotbellamy** [comment] 2019-03-27 00:31
As silly as that would have been, would have been better than my mistake.  I was using localhost and didn't realize I had subsequent localhost entries in my hosts file that didn't allow it to work correctly in my browser.  Using 127.0.0.1 directly worked.

That said, is there any concern with "illegal reflective class operation" warnings?  Older posts suggested it might.

Thanks

**Comment by zubcevic** [comment] 2019-03-27 06:02
I think it is certainly a kind of an issue. At least the increased frequency of JDK releases has some impacts. I have noticed that using JDK12, you cannot build the application anymore. We will have to make some changes to some of the maven plugins used. 
And also if you want to organise a workshop, you could spend some time in getting everybody started using the right JRE. I am looking into launch4J to turn the applications into executables with their own working JRE bundled inside. At least for those that cannot use docker or vagrant/virtual box.
Right now I am still using Java 8 in workshops, because it is more present on participants environments and the code can still be compiled for Java 8 when you change the two main pom.xml that are now set to expect Java 11

**Comment by davewichers** [comment] 2019-06-11 19:42
These WARNINGS are caused by using Java 11. However, they don't break anything (yet). Maybe in Java 12, as the previous comment said, but WebGoat works fine in Java 11. You should close this ticket, and open a new one that talks about eliminating these warnings. In fact, it MAY be required to fix these to get it to work with Java 12. (not sure as I haven't tried using Java 12 yet).

**Comment by nbaars** [comment] 2019-09-10 12:07
> Right now I am still using Java 8 in workshops, because it is more present on participants environments and the code can still be compiled for Java 8 when you change the two main pom.xml that are now set to expect Java 11

Java 11 is available as a zip file, so you don't have to go through a complete installation process anymore, just download and unzip and run WebGoat with that specific Java 11 download. That's how I usually approach a workshop as getting Docker installed and running is much more work as to just having participants download Java 11 zipfile :-)

**Closed by nbaars** 2019-09-10 12:07 UTC
