### ISSUE TITLE
Session Management Flaws - Spoof an Authentication Cookie render issue

### ISSUE THREAD

**Issue by mayhew64** [WebGoat/WebGoat#181] opened 2016-01-30 17:28 UTC
Pressing the refresh button in the lesson content is the only way to check if the setting of the cookie authenticates you as alice.  When pressing the button the screen render is whacky.

![image](https://cloud.githubusercontent.com/assets/3689202/12697252/ebba7142-c74c-11e5-8bc3-64547b47b03c.png)

![image](https://cloud.githubusercontent.com/assets/3689202/12697256/fbb44a46-c74c-11e5-8101-4e2e10a4aaad.png)

**Comment by span** [comment] 2016-02-11 23:15
I am unable to reproduce this with the latest lessons and the latest commits from `develop` branch using Firefox and Chrome.

I have seen the issue on other parts of WebGoat occuring seemingly randomly but I suspect they come more frequently when I refresh the same page although the server have been restarted in between. 

There has also been some broken layouts when intercepting requests and forgetting to forward them in time.

Anyway, you might want to have another look at this with a clean build.

**Comment by span** [comment] 2016-03-02 12:00
Merged and still not able to reproduce. Voting to close if someone else can try it as well.

**Comment by nbaars** [comment] 2016-03-18 12:17
Agreed, tested and refresh works ok. Closing this issue

**Closed by nbaars** 2016-03-18 12:17 UTC
Labels: WebGoat-Lessons, WebGoat-UI
