### ISSUE TITLE
WebGoat Java 11 does not load propperly

### ISSUE THREAD

**Issue by anagfar** [WebGoat/WebGoat#748] opened 2020-01-17 17:28 UTC
Hi! I tried with M24, M25 and M26 version ...

jdk-11.0.6

Every time, do you log in the menu shown as follows (capture attached) does anyone know how to fix it? Thank you

![load](https://user-images.githubusercontent.com/54401161/72632559-cf882c00-3956-11ea-9e76-4d1a91f997cc.PNG)

**Comment by anagfar** [comment] 2020-01-17 17:28
Forgot to say, I'm using Windows 10

**Comment by zubcevic** [comment] 2020-01-18 10:15
This does not look like the screens I am getting on Windows 10. Which browser are you using? Did you try on another machine? Alternatively, you can try the Docker desktop for windows and run the docker container. The issues shown are not reproducable on my windows 10 machine

**Comment by anagfar** [comment] 2020-01-18 10:22
Hi! thank you for your answer.

I've tried with Firefox and Chrome (same result) and with IE (IE shows the menu correctly...)..

I've installed jdk-11.0.6 and the execution 

"path_to_jdk" -jar "path_to_jar"

Older versions, before M24 shows web console correctly....

It is very much strange...

Thank you

**Comment by zubcevic** [comment] 2020-03-30 15:38
can you show the WebGoat log for this typical situation? And perhaps also show a screenshot from the network section of your browser developer tools. Just to see if it could be browser cache related

**Comment by zubcevic** [comment] 2020-04-03 10:22
As the issue is not described clearly, I have to close the issue. Feel free to reopen it with more clear information

**Closed by zubcevic** 2020-04-03 10:22 UTC
Labels: waiting for input
