### ISSUE TITLE
Bypass Client Side Javascript Validation

### ISSUE THREAD

**Issue by ghost** [WebGoat/WebGoat#317] opened 2017-01-26 10:21 UTC
In the last release the type of the submit button in this lesson was changed from "BUTTON" to "SUBMIT". Now, the lesson is easily passed by just changing the values in the input fields, as the client side JavaScript does not "preventDefault" or otherwise hinders the submission of the input.

**Comment by aolle** [comment] 2021-09-29 21:59
Actually, the lesson cannot be bypassed by just changing the values because a hidden value is sent on submit.

Although the event target is propagated in the DOM tree and the form submitted anyway, currently there is no need of preventDefault or stopPropagation.

If you have a working reproducer with the latest version, please share it.

For now, I will go ahead an close the issue.

**Closed by aolle** 2021-09-29 21:59 UTC
Labels: help wanted
