### ISSUE TITLE
Firefox and Edge miss one lesson in Menu

### ISSUE THREAD

**Issue by nbaars** [WebGoat/WebGoat#49] opened 2015-08-24 23:49 UTC
Just noticed when I was fixing an issue so I made a side by side comparison. All point to localhost and I used FireFox(left) Edge (middle) and Chrome(right) and Chrome has one more lesson displayed in the menu.

Edge and Firefox each miss a different lesson.

![lesson-menu](https://cloud.githubusercontent.com/assets/493861/9455435/7fbcf850-4acb-11e5-8143-74427d9f3a5e.jpg)

**Comment by misfir3** [comment] 2015-09-09 17:24
Started to look at this.  Short version of the problem is that the browsers are receiving different responses from the call to /lessonmenu.mvc

Firefox starts out as:
0 Object { name="Introduction",  type="CATEGORY",  children=[2],  more...}
1 Object { name="General",  type="CATEGORY",  children=[1],  more...}
2 Object { name="Access Control Flaws",  type="CATEGORY",  children=[3],  more...}
3 Object { name="AJAX Security",  type="CATEGORY",  children=[9],  more...}

Chrome starts out as:
0: {name: "Introduction", type: "CATEGORY",…}
1: {name: "Access Control Flaws", type: "CATEGORY",…}
2: {name: "AJAX Security", type: "CATEGORY",…}

Chrome does not receive the 'General category in its response from the server. Will look for root cause/solution.

**Comment by misfir3** [comment] 2015-09-13 02:59
Re-ran from fresh build in Chromium, Chrome and FF ... all categories accounted for:

![image](https://cloud.githubusercontent.com/assets/5103241/9834992/9aef75d2-59a1-11e5-8947-849c64de308c.png)

@nbaars  can you look again with Edge vs FF and/or Chrome (Don't have a windows VM or time to set one up currently)? Maybe someone with a Mac, check Safari?

**Comment by mayhew64** [comment] 2015-09-16 11:36
Comfirmed that chrome was missing code quality category and firefox and safari were not.

**Comment by dougmorato** [comment] 2015-09-16 12:51
I would like to add that we can perform cross-os and cross-browser testing already using the SauceLabs/Selenium integration tests.... we just need to write more tests for it.


Please check this link for the current OS/Browser capabilities: https://docs.saucelabs.com/reference/platforms-configurator/#/

__These tests even include a screenshot of the results automatically.__

Currently, we are only testing for Windows 7 and Chrome v41 = https://github.com/WebGoat/WebGoat/blob/master/webgoat-container/src/test/java/org/owasp/webgoat/plugins/WebGoatIT.java#L124 

SauceLabs is a free service for open-source projects. Just let me know (via slack or email) which email do you want to use and I will send the invite to join the webgoat account in SauceLabs

**Comment by misfir3** [comment] 2015-09-16 16:50
@dougmorato, Would like to try sauceLabs later, but

All ... if  you can reproduce this, also let me know how you are running it (via maven tomcat, regular tomcat or otherwise). Beginning to think that may factor in. Running from same server source, I could not reproduce. Have had some trouble lately with:
``` bash
cd WebGoat
mvn -pl webgoat-container tomcat7:run-war
```
(will create separate issue on that)
and reverted to standard tomcat for now (results from above reflect that). Is everyone else running via the tomcat7 plugin? If so, try with full tomcat and see if it differs.

**Comment by misfir3** [comment] 2015-09-18 02:46
So, this happens when running under the tomcat:run-war scenario ... confirmed that tonight. Does not happen running under regular tomcat. Have not tried executable jar.  The JSON is actually different, so this is happening in the service.

**Comment by mayhew64** [comment] 2015-09-18 11:07
Do you mean tomcat:run-war or tomcat7:run-war?  Not that it matters as the issue happens with Tomcat 7.

**Comment by misfir3** [comment] 2015-09-18 12:44
tomcat7:run-war ... updated comment above as well.

**Comment by misfir3** [comment] 2015-09-18 22:46
Closing for now. If anyone notices this again, please re-open.

**Closed by misfir3** 2015-09-18 22:46 UTC
Labels: bug, WebGoat-UI
